//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Class4
{
	public virtual Class1 Class1
	{
		get;
		set;
	}

	public virtual Class3 Class3
	{
		get;
		set;
	}

	public virtual Class2 Class2
	{
		get;
		set;
	}

}

